linters:
  enable-all: true
  disable:
    # deprecated
    - maligned
    - scopelint
    - interfacer
    - golint
    - ifshort
    - deadcode
    - nosnakecase
    - structcheck
    - varcheck
    # unused
    - exhaustivestruct
    - exhaustruct
    - nlreturn
    - tagalign
    - depguard
    - godot
    - lll

run:
  timeout: 3m