{
 "title": "Auth Proxy",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "User Queries",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "authproxy_db_query_time_seconds_count{cache=\"users\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Queries",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "authproxy_db_query_time_seconds_count{cache=\"servers\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "authproxy_uptime_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SQL Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "authproxy_db_query_errors_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users Cached",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "authproxy_cache_gauges{cache=\"users\", gauge=\"size\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Servers Cached",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "authproxy_cache_gauges{cache=\"servers\", gauge=\"size\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Auth Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(authproxy_request_time_seconds_count[1m])",
     "legendFormat": "{{cache}} auth"
    }
   ]
  },
  {
   "title": "HTTP Request Duration (Servers)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "avg by(le) (rate(authproxy_request_time_seconds_bucket{cache=\"servers\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Duration (Users)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "avg by(le) (rate(authproxy_request_time_seconds_bucket{cache=\"users\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "SQL Queries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "increase(authproxy_db_query_time_seconds_count[1m])",
     "legendFormat": "{{cache}} queries"
    }
   ]
  },
  {
   "title": "SQL Anomalies",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "increase(authproxy_db_query_missing_total[5m])",
     "legendFormat": "{{cache}} missing"
    }
   ]
  },
  {
   "title": "SQL Request Duration (Servers)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "avg by(le) (rate(authproxy_db_query_time_seconds_bucket{cache=\"servers\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SQL Request Duration (Users)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "avg by(le) (increase(authproxy_db_query_time_seconds_bucket{cache=\"users\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Server Cache",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "rate(authproxy_cache_counters{cache=\"servers\", counter=\"gets\"}[1m])",
     "legendFormat": "{{cache}} {{counter}}"
    },
    {
     "expr": "rate(authproxy_cache_counters{cache=\"servers\", counter=\"hits\"}[1m])",
     "legendFormat": "{{cache}} {{counter}}"
    },
    {
     "expr": "rate(authproxy_cache_counters{cache=\"servers\", counter=\"misses\"}[1m])",
     "legendFormat": "{{cache}} {{counter}}"
    },
    {
     "expr": "rate(authproxy_cache_counters{cache=\"servers\", counter=\"deletes\"}[1m])",
     "legendFormat": "{{cache}} {{counter}}"
    },
    {
     "expr": "rate(authproxy_cache_counters{cache=\"servers\", counter=\"delmiss\"}[1m])",
     "legendFormat": "{{cache}} {{counter}}"
    },
    {
     "expr": "rate(authproxy_cache_counters{cache=\"servers\", counter=\"pruned\"}[1m])",
     "legendFormat": "{{cache}} {{counter}}"
    },
    {
     "expr": "rate(authproxy_cache_counters{cache=\"servers\", counter=\"prunes\"}[1m])",
     "legendFormat": "{{cache}} {{counter}}"
    },
    {
     "expr": "rate(authproxy_cache_counters{cache=\"servers\", counter=\"updates\"}[1m])",
     "legendFormat": "{{cache}} {{counter}}"
    },
    {
     "expr": "rate(authproxy_cache_counters{cache=\"servers\", counter=\"saves\"}[1m])",
     "legendFormat": "{{cache}} {{counter}}"
    }
   ]
  },
  {
   "title": "User Cache",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "rate(authproxy_cache_counters{cache=\"users\", counter=\"gets\"}[1m])",
     "legendFormat": "{{cache}} {{counter}}"
    },
    {
     "expr": "rate(authproxy_cache_counters{cache=\"users\", counter=\"hits\"}[1m])",
     "legendFormat": "{{cache}} {{counter}}"
    },
    {
     "expr": "rate(authproxy_cache_counters{cache=\"users\", counter=\"misses\"}[1m])",
     "legendFormat": "{{cache}} {{counter}}"
    },
    {
     "expr": "rate(authproxy_cache_counters{cache=\"users\", counter=\"deletes\"}[1m])",
     "legendFormat": "{{cache}} {{counter}}"
    },
    {
     "expr": "rate(authproxy_cache_counters{cache=\"users\", counter=\"delmiss\"}[1m])",
     "legendFormat": "{{cache}} {{counter}}"
    },
    {
     "expr": "rate(authproxy_cache_counters{cache=\"users\", counter=\"pruned\"}[1m])",
     "legendFormat": "{{cache}} {{counter}}"
    },
    {
     "expr": "rate(authproxy_cache_counters{cache=\"users\", counter=\"prunes\"}[1m])",
     "legendFormat": "{{cache}} {{counter}}"
    },
    {
     "expr": "rate(authproxy_cache_counters{cache=\"users\", counter=\"updates\"}[1m])",
     "legendFormat": "{{cache}} {{counter}}"
    },
    {
     "expr": "rate(authproxy_cache_counters{cache=\"users\", counter=\"saves\"}[1m])",
     "legendFormat": "{{cache}} {{counter}}"
    }
   ]
  }
 ]
}